### ISSUE TITLE
When an exception occurs, the connection cannot be recycled

### ISSUE THREAD

**Issue by zhangtianxiao** [cretz/pgnio#16]
```java
Caused by: pgnio.DriverException$NoConversion: No conversion defined for class [Ljava.lang.Object;
	at pgnio.ParamWriter.write(ParamWriter.java:75)
	at pgnio.ParamWriter.write(ParamWriter.java:63)
	at pgnio.QueryBuildConnection$Prepared.sendBindWithConvertedParams(QueryBuildConnection.java:146)
```

then, when I call `ds.returnConnection`, will happen

```java
java.lang.IllegalStateException: Length already started
	at pgnio.BufWriter$Simple.writeLengthIntBegin(BufWriter.java:101)
	at pgnio.QueryBuildConnection.sendSync(QueryBuildConnection.java:57)
	at pgnio.QueryBuildConnection.done(QueryBuildConnection.java:71)
	at pgnio.QueryBuildConnection.reset(QueryBuildConnection.java:66)
	at pgnio.Connection$Started.fullReset(Connection.java:438)
	at pgnio.Connection$Started.fullReset(Connection.java:438)
	at pgnio.ConnectionPool.returnConnection(ConnectionPool.java:139)
```

**Comment by cretz** [comment]
It appears I am not cleaning up properly on exception after reading only part of a type. I am not actively working on the project, so I cannot say when it'll be fixed (PRs welcome of course).
